In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

##### import data

In [2]:
df = pd.read_csv('../data/Churn_Modelling.csv')

x = df.iloc[:, 3:-1].to_numpy()
y = df.iloc[:, -1].to_numpy()

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

#### data preprocessing

##### handle missing data

In [4]:
# no missing data
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

##### encode categories

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

ct = ColumnTransformer(transformers = [('ohe', OneHotEncoder(drop = 'first'), [1, 2])], remainder = 'passthrough')

x = ct.fit_transform(x)

In [6]:
print(x[:10])

[[0.0 0.0 0.0 619 42 2 0.0 1 1 1 101348.88]
 [0.0 1.0 0.0 608 41 1 83807.86 1 0 1 112542.58]
 [0.0 0.0 0.0 502 42 8 159660.8 3 1 0 113931.57]
 [0.0 0.0 0.0 699 39 1 0.0 2 0 0 93826.63]
 [0.0 1.0 0.0 850 43 2 125510.82 1 1 1 79084.1]
 [0.0 1.0 1.0 645 44 8 113755.78 2 1 0 149756.71]
 [0.0 0.0 1.0 822 50 7 0.0 2 1 1 10062.8]
 [1.0 0.0 0.0 376 29 4 115046.74 4 1 0 119346.88]
 [0.0 0.0 1.0 501 44 4 142051.07 2 0 1 74940.5]
 [0.0 0.0 1.0 684 27 2 134603.88 1 1 1 71725.73]]


##### split data

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

##### feature scaling

> In case of neural netwroks, all the features need to be scaled, even categorical features

In [8]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

#### build & train model

##### build Artificial Neural Network

In [9]:
ann = tf.keras.models.Sequential() # initialize

In [10]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) # 1st hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) # 2nd hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid')) # output layer

> for multiple categories, units = (no. of categories), activation = 'softmax'

> for regression, activation = 'Linear' (Default)

##### train model

> for multiple categories, loss = 'categorical_crossentropy'

> for regression, loss = 'mse' or 'mae' or 'huber'

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 40)

Epoch 1/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7692 - loss: 0.5857
Epoch 2/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.4683
Epoch 3/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.4439
Epoch 4/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.4343
Epoch 5/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.4278
Epoch 6/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.4216
Epoch 7/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.4150
Epoch 8/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.4083
Epoch 9/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.4014
Epoch 10/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7960 - loss: 0.3953
Epoch 11/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8067 - loss: 0.3905
Epoch 12/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

#### model evaluation

##### predict on a single input

In [15]:
customer = [[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]]

In [16]:
customer = np.array(customer, dtype = 'object')

customer = ss.transform(ct.transform(customer))

In [17]:
print(ann.predict(customer) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
[[False]]


##### predict test results

In [18]:
y_pred = (ann.predict(x_test) > 0.5).astype(int)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  


##### confusion matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

print('confusion matrix:\n', confusion_matrix(y_test, y_pred))
print('\naccuracy:', accuracy_score(y_test, y_pred))
print('f1 score:', f1_score(y_test, y_pred))

confusion matrix:
 [[1513   82]
 [ 191  214]]

accuracy: 0.8635
f1 score: 0.6105563480741797
